//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CPP14Parser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CPP14Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ICPP14ParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslationUnit([NotNull] CPP14Parser.TranslationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslationUnit([NotNull] CPP14Parser.TranslationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] CPP14Parser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] CPP14Parser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.idExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdExpression([NotNull] CPP14Parser.IdExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.idExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdExpression([NotNull] CPP14Parser.IdExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.unqualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnqualifiedId([NotNull] CPP14Parser.UnqualifiedIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.unqualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnqualifiedId([NotNull] CPP14Parser.UnqualifiedIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.qualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedId([NotNull] CPP14Parser.QualifiedIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.qualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedId([NotNull] CPP14Parser.QualifiedIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.nestedNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestedNameSpecifier([NotNull] CPP14Parser.NestedNameSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.nestedNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestedNameSpecifier([NotNull] CPP14Parser.NestedNameSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaExpression([NotNull] CPP14Parser.LambdaExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaExpression([NotNull] CPP14Parser.LambdaExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.lambdaIntroducer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaIntroducer([NotNull] CPP14Parser.LambdaIntroducerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.lambdaIntroducer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaIntroducer([NotNull] CPP14Parser.LambdaIntroducerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.lambdaCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaCapture([NotNull] CPP14Parser.LambdaCaptureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.lambdaCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaCapture([NotNull] CPP14Parser.LambdaCaptureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.captureDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaptureDefault([NotNull] CPP14Parser.CaptureDefaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.captureDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaptureDefault([NotNull] CPP14Parser.CaptureDefaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.captureList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaptureList([NotNull] CPP14Parser.CaptureListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.captureList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaptureList([NotNull] CPP14Parser.CaptureListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCapture([NotNull] CPP14Parser.CaptureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCapture([NotNull] CPP14Parser.CaptureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.simpleCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleCapture([NotNull] CPP14Parser.SimpleCaptureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.simpleCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleCapture([NotNull] CPP14Parser.SimpleCaptureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.initcapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitcapture([NotNull] CPP14Parser.InitcaptureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.initcapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitcapture([NotNull] CPP14Parser.InitcaptureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.lambdaDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaDeclarator([NotNull] CPP14Parser.LambdaDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.lambdaDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaDeclarator([NotNull] CPP14Parser.LambdaDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] CPP14Parser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] CPP14Parser.PostfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.typeIdOfTheTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeIdOfTheTypeId([NotNull] CPP14Parser.TypeIdOfTheTypeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.typeIdOfTheTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeIdOfTheTypeId([NotNull] CPP14Parser.TypeIdOfTheTypeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] CPP14Parser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] CPP14Parser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.pseudoDestructorName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPseudoDestructorName([NotNull] CPP14Parser.PseudoDestructorNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.pseudoDestructorName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPseudoDestructorName([NotNull] CPP14Parser.PseudoDestructorNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] CPP14Parser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] CPP14Parser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] CPP14Parser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] CPP14Parser.UnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.newExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewExpression([NotNull] CPP14Parser.NewExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.newExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewExpression([NotNull] CPP14Parser.NewExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.newPlacement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewPlacement([NotNull] CPP14Parser.NewPlacementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.newPlacement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewPlacement([NotNull] CPP14Parser.NewPlacementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.newTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewTypeId([NotNull] CPP14Parser.NewTypeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.newTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewTypeId([NotNull] CPP14Parser.NewTypeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.newDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewDeclarator([NotNull] CPP14Parser.NewDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.newDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewDeclarator([NotNull] CPP14Parser.NewDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.noPointerNewDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoPointerNewDeclarator([NotNull] CPP14Parser.NoPointerNewDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.noPointerNewDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoPointerNewDeclarator([NotNull] CPP14Parser.NoPointerNewDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.newInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewInitializer([NotNull] CPP14Parser.NewInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.newInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewInitializer([NotNull] CPP14Parser.NewInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.deleteExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteExpression([NotNull] CPP14Parser.DeleteExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.deleteExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteExpression([NotNull] CPP14Parser.DeleteExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.noExceptExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoExceptExpression([NotNull] CPP14Parser.NoExceptExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.noExceptExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoExceptExpression([NotNull] CPP14Parser.NoExceptExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastExpression([NotNull] CPP14Parser.CastExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastExpression([NotNull] CPP14Parser.CastExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.pointerMemberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerMemberExpression([NotNull] CPP14Parser.PointerMemberExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.pointerMemberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerMemberExpression([NotNull] CPP14Parser.PointerMemberExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] CPP14Parser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] CPP14Parser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] CPP14Parser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] CPP14Parser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftExpression([NotNull] CPP14Parser.ShiftExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftExpression([NotNull] CPP14Parser.ShiftExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftOperator([NotNull] CPP14Parser.ShiftOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftOperator([NotNull] CPP14Parser.ShiftOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] CPP14Parser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] CPP14Parser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] CPP14Parser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] CPP14Parser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpression([NotNull] CPP14Parser.AndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpression([NotNull] CPP14Parser.AndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclusiveOrExpression([NotNull] CPP14Parser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclusiveOrExpression([NotNull] CPP14Parser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclusiveOrExpression([NotNull] CPP14Parser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclusiveOrExpression([NotNull] CPP14Parser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] CPP14Parser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] CPP14Parser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] CPP14Parser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] CPP14Parser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalExpression([NotNull] CPP14Parser.ConditionalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalExpression([NotNull] CPP14Parser.ConditionalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] CPP14Parser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] CPP14Parser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperator([NotNull] CPP14Parser.AssignmentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperator([NotNull] CPP14Parser.AssignmentOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CPP14Parser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CPP14Parser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpression([NotNull] CPP14Parser.ConstantExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpression([NotNull] CPP14Parser.ConstantExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CPP14Parser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CPP14Parser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabeledStatement([NotNull] CPP14Parser.LabeledStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabeledStatement([NotNull] CPP14Parser.LabeledStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] CPP14Parser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] CPP14Parser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundStatement([NotNull] CPP14Parser.CompoundStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundStatement([NotNull] CPP14Parser.CompoundStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.statementSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementSeq([NotNull] CPP14Parser.StatementSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.statementSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementSeq([NotNull] CPP14Parser.StatementSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectionStatement([NotNull] CPP14Parser.SelectionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectionStatement([NotNull] CPP14Parser.SelectionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] CPP14Parser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] CPP14Parser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIterationStatement([NotNull] CPP14Parser.IterationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIterationStatement([NotNull] CPP14Parser.IterationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.forInitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForInitStatement([NotNull] CPP14Parser.ForInitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.forInitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForInitStatement([NotNull] CPP14Parser.ForInitStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.forRangeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForRangeDeclaration([NotNull] CPP14Parser.ForRangeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.forRangeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForRangeDeclaration([NotNull] CPP14Parser.ForRangeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.forRangeInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForRangeInitializer([NotNull] CPP14Parser.ForRangeInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.forRangeInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForRangeInitializer([NotNull] CPP14Parser.ForRangeInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpStatement([NotNull] CPP14Parser.JumpStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpStatement([NotNull] CPP14Parser.JumpStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationStatement([NotNull] CPP14Parser.DeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationStatement([NotNull] CPP14Parser.DeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.declarationseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationseq([NotNull] CPP14Parser.DeclarationseqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.declarationseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationseq([NotNull] CPP14Parser.DeclarationseqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] CPP14Parser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] CPP14Parser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.blockDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockDeclaration([NotNull] CPP14Parser.BlockDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.blockDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockDeclaration([NotNull] CPP14Parser.BlockDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.aliasDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAliasDeclaration([NotNull] CPP14Parser.AliasDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.aliasDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAliasDeclaration([NotNull] CPP14Parser.AliasDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.simpleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleDeclaration([NotNull] CPP14Parser.SimpleDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.simpleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleDeclaration([NotNull] CPP14Parser.SimpleDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticAssertDeclaration([NotNull] CPP14Parser.StaticAssertDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticAssertDeclaration([NotNull] CPP14Parser.StaticAssertDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.emptyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyDeclaration([NotNull] CPP14Parser.EmptyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.emptyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyDeclaration([NotNull] CPP14Parser.EmptyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.attributeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeDeclaration([NotNull] CPP14Parser.AttributeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.attributeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeDeclaration([NotNull] CPP14Parser.AttributeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.declSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclSpecifier([NotNull] CPP14Parser.DeclSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.declSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclSpecifier([NotNull] CPP14Parser.DeclSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.declSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclSpecifierSeq([NotNull] CPP14Parser.DeclSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.declSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclSpecifierSeq([NotNull] CPP14Parser.DeclSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStorageClassSpecifier([NotNull] CPP14Parser.StorageClassSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStorageClassSpecifier([NotNull] CPP14Parser.StorageClassSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSpecifier([NotNull] CPP14Parser.FunctionSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSpecifier([NotNull] CPP14Parser.FunctionSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedefName([NotNull] CPP14Parser.TypedefNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedefName([NotNull] CPP14Parser.TypedefNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] CPP14Parser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] CPP14Parser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.trailingTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrailingTypeSpecifier([NotNull] CPP14Parser.TrailingTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.trailingTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrailingTypeSpecifier([NotNull] CPP14Parser.TrailingTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.typeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifierSeq([NotNull] CPP14Parser.TypeSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.typeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifierSeq([NotNull] CPP14Parser.TypeSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.trailingTypeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrailingTypeSpecifierSeq([NotNull] CPP14Parser.TrailingTypeSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.trailingTypeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrailingTypeSpecifierSeq([NotNull] CPP14Parser.TrailingTypeSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.simpleTypeLengthModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleTypeLengthModifier([NotNull] CPP14Parser.SimpleTypeLengthModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.simpleTypeLengthModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleTypeLengthModifier([NotNull] CPP14Parser.SimpleTypeLengthModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.simpleTypeSignednessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleTypeSignednessModifier([NotNull] CPP14Parser.SimpleTypeSignednessModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.simpleTypeSignednessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleTypeSignednessModifier([NotNull] CPP14Parser.SimpleTypeSignednessModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleTypeSpecifier([NotNull] CPP14Parser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleTypeSpecifier([NotNull] CPP14Parser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.theTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTheTypeName([NotNull] CPP14Parser.TheTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.theTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTheTypeName([NotNull] CPP14Parser.TheTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.decltypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecltypeSpecifier([NotNull] CPP14Parser.DecltypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.decltypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecltypeSpecifier([NotNull] CPP14Parser.DecltypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.elaboratedTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElaboratedTypeSpecifier([NotNull] CPP14Parser.ElaboratedTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.elaboratedTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElaboratedTypeSpecifier([NotNull] CPP14Parser.ElaboratedTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumName([NotNull] CPP14Parser.EnumNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumName([NotNull] CPP14Parser.EnumNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumSpecifier([NotNull] CPP14Parser.EnumSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumSpecifier([NotNull] CPP14Parser.EnumSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.enumHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumHead([NotNull] CPP14Parser.EnumHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.enumHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumHead([NotNull] CPP14Parser.EnumHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.opaqueEnumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpaqueEnumDeclaration([NotNull] CPP14Parser.OpaqueEnumDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.opaqueEnumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpaqueEnumDeclaration([NotNull] CPP14Parser.OpaqueEnumDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.enumkey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumkey([NotNull] CPP14Parser.EnumkeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.enumkey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumkey([NotNull] CPP14Parser.EnumkeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.enumbase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumbase([NotNull] CPP14Parser.EnumbaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.enumbase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumbase([NotNull] CPP14Parser.EnumbaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumeratorList([NotNull] CPP14Parser.EnumeratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumeratorList([NotNull] CPP14Parser.EnumeratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.enumeratorDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumeratorDefinition([NotNull] CPP14Parser.EnumeratorDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.enumeratorDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumeratorDefinition([NotNull] CPP14Parser.EnumeratorDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerator([NotNull] CPP14Parser.EnumeratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerator([NotNull] CPP14Parser.EnumeratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.namespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceName([NotNull] CPP14Parser.NamespaceNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.namespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceName([NotNull] CPP14Parser.NamespaceNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.originalNamespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOriginalNamespaceName([NotNull] CPP14Parser.OriginalNamespaceNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.originalNamespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOriginalNamespaceName([NotNull] CPP14Parser.OriginalNamespaceNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.namespaceDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceDefinition([NotNull] CPP14Parser.NamespaceDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.namespaceDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceDefinition([NotNull] CPP14Parser.NamespaceDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.namespaceAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceAlias([NotNull] CPP14Parser.NamespaceAliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.namespaceAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceAlias([NotNull] CPP14Parser.NamespaceAliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.namespaceAliasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceAliasDefinition([NotNull] CPP14Parser.NamespaceAliasDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.namespaceAliasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceAliasDefinition([NotNull] CPP14Parser.NamespaceAliasDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.qualifiednamespacespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiednamespacespecifier([NotNull] CPP14Parser.QualifiednamespacespecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.qualifiednamespacespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiednamespacespecifier([NotNull] CPP14Parser.QualifiednamespacespecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.usingDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingDeclaration([NotNull] CPP14Parser.UsingDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.usingDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingDeclaration([NotNull] CPP14Parser.UsingDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.usingDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingDirective([NotNull] CPP14Parser.UsingDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.usingDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingDirective([NotNull] CPP14Parser.UsingDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.asmDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmDefinition([NotNull] CPP14Parser.AsmDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.asmDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmDefinition([NotNull] CPP14Parser.AsmDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.linkageSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkageSpecification([NotNull] CPP14Parser.LinkageSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.linkageSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkageSpecification([NotNull] CPP14Parser.LinkageSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.attributeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeSpecifierSeq([NotNull] CPP14Parser.AttributeSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.attributeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeSpecifierSeq([NotNull] CPP14Parser.AttributeSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.attributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeSpecifier([NotNull] CPP14Parser.AttributeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.attributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeSpecifier([NotNull] CPP14Parser.AttributeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.alignmentspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlignmentspecifier([NotNull] CPP14Parser.AlignmentspecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.alignmentspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlignmentspecifier([NotNull] CPP14Parser.AlignmentspecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.attributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeList([NotNull] CPP14Parser.AttributeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.attributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeList([NotNull] CPP14Parser.AttributeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] CPP14Parser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] CPP14Parser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.attributeNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeNamespace([NotNull] CPP14Parser.AttributeNamespaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.attributeNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeNamespace([NotNull] CPP14Parser.AttributeNamespaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.attributeArgumentClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeArgumentClause([NotNull] CPP14Parser.AttributeArgumentClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.attributeArgumentClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeArgumentClause([NotNull] CPP14Parser.AttributeArgumentClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.balancedTokenSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBalancedTokenSeq([NotNull] CPP14Parser.BalancedTokenSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.balancedTokenSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBalancedTokenSeq([NotNull] CPP14Parser.BalancedTokenSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.balancedtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBalancedtoken([NotNull] CPP14Parser.BalancedtokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.balancedtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBalancedtoken([NotNull] CPP14Parser.BalancedtokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclaratorList([NotNull] CPP14Parser.InitDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclaratorList([NotNull] CPP14Parser.InitDeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclarator([NotNull] CPP14Parser.InitDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclarator([NotNull] CPP14Parser.InitDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] CPP14Parser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] CPP14Parser.DeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.pointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerDeclarator([NotNull] CPP14Parser.PointerDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.pointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerDeclarator([NotNull] CPP14Parser.PointerDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.noPointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoPointerDeclarator([NotNull] CPP14Parser.NoPointerDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.noPointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoPointerDeclarator([NotNull] CPP14Parser.NoPointerDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.parametersAndQualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParametersAndQualifiers([NotNull] CPP14Parser.ParametersAndQualifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.parametersAndQualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParametersAndQualifiers([NotNull] CPP14Parser.ParametersAndQualifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.trailingReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrailingReturnType([NotNull] CPP14Parser.TrailingReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.trailingReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrailingReturnType([NotNull] CPP14Parser.TrailingReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.pointerOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerOperator([NotNull] CPP14Parser.PointerOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.pointerOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerOperator([NotNull] CPP14Parser.PointerOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.cvqualifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCvqualifierseq([NotNull] CPP14Parser.CvqualifierseqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.cvqualifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCvqualifierseq([NotNull] CPP14Parser.CvqualifierseqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.cvQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCvQualifier([NotNull] CPP14Parser.CvQualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.cvQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCvQualifier([NotNull] CPP14Parser.CvQualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.refqualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefqualifier([NotNull] CPP14Parser.RefqualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.refqualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefqualifier([NotNull] CPP14Parser.RefqualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.declaratorid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaratorid([NotNull] CPP14Parser.DeclaratoridContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.declaratorid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaratorid([NotNull] CPP14Parser.DeclaratoridContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.theTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTheTypeId([NotNull] CPP14Parser.TheTypeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.theTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTheTypeId([NotNull] CPP14Parser.TheTypeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbstractDeclarator([NotNull] CPP14Parser.AbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbstractDeclarator([NotNull] CPP14Parser.AbstractDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.pointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerAbstractDeclarator([NotNull] CPP14Parser.PointerAbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.pointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerAbstractDeclarator([NotNull] CPP14Parser.PointerAbstractDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.noPointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoPointerAbstractDeclarator([NotNull] CPP14Parser.NoPointerAbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.noPointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoPointerAbstractDeclarator([NotNull] CPP14Parser.NoPointerAbstractDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.abstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbstractPackDeclarator([NotNull] CPP14Parser.AbstractPackDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.abstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbstractPackDeclarator([NotNull] CPP14Parser.AbstractPackDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.noPointerAbstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoPointerAbstractPackDeclarator([NotNull] CPP14Parser.NoPointerAbstractPackDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.noPointerAbstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoPointerAbstractPackDeclarator([NotNull] CPP14Parser.NoPointerAbstractPackDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.parameterDeclarationClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclarationClause([NotNull] CPP14Parser.ParameterDeclarationClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.parameterDeclarationClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclarationClause([NotNull] CPP14Parser.ParameterDeclarationClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.parameterDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclarationList([NotNull] CPP14Parser.ParameterDeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.parameterDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclarationList([NotNull] CPP14Parser.ParameterDeclarationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclaration([NotNull] CPP14Parser.ParameterDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclaration([NotNull] CPP14Parser.ParameterDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] CPP14Parser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] CPP14Parser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionBody([NotNull] CPP14Parser.FunctionBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionBody([NotNull] CPP14Parser.FunctionBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] CPP14Parser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] CPP14Parser.InitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.braceOrEqualInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBraceOrEqualInitializer([NotNull] CPP14Parser.BraceOrEqualInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.braceOrEqualInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBraceOrEqualInitializer([NotNull] CPP14Parser.BraceOrEqualInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.initializerClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializerClause([NotNull] CPP14Parser.InitializerClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.initializerClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializerClause([NotNull] CPP14Parser.InitializerClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializerList([NotNull] CPP14Parser.InitializerListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializerList([NotNull] CPP14Parser.InitializerListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.bracedInitList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracedInitList([NotNull] CPP14Parser.BracedInitListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.bracedInitList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracedInitList([NotNull] CPP14Parser.BracedInitListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassName([NotNull] CPP14Parser.ClassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassName([NotNull] CPP14Parser.ClassNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.classSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassSpecifier([NotNull] CPP14Parser.ClassSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.classSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassSpecifier([NotNull] CPP14Parser.ClassSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.classHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassHead([NotNull] CPP14Parser.ClassHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.classHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassHead([NotNull] CPP14Parser.ClassHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.classHeadName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassHeadName([NotNull] CPP14Parser.ClassHeadNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.classHeadName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassHeadName([NotNull] CPP14Parser.ClassHeadNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.classVirtSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassVirtSpecifier([NotNull] CPP14Parser.ClassVirtSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.classVirtSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassVirtSpecifier([NotNull] CPP14Parser.ClassVirtSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.classKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassKey([NotNull] CPP14Parser.ClassKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.classKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassKey([NotNull] CPP14Parser.ClassKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.memberSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberSpecification([NotNull] CPP14Parser.MemberSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.memberSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberSpecification([NotNull] CPP14Parser.MemberSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.memberdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberdeclaration([NotNull] CPP14Parser.MemberdeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.memberdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberdeclaration([NotNull] CPP14Parser.MemberdeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.memberDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclaratorList([NotNull] CPP14Parser.MemberDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.memberDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclaratorList([NotNull] CPP14Parser.MemberDeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.memberDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclarator([NotNull] CPP14Parser.MemberDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.memberDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclarator([NotNull] CPP14Parser.MemberDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.virtualSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVirtualSpecifierSeq([NotNull] CPP14Parser.VirtualSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.virtualSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVirtualSpecifierSeq([NotNull] CPP14Parser.VirtualSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.virtualSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVirtualSpecifier([NotNull] CPP14Parser.VirtualSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.virtualSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVirtualSpecifier([NotNull] CPP14Parser.VirtualSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.pureSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPureSpecifier([NotNull] CPP14Parser.PureSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.pureSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPureSpecifier([NotNull] CPP14Parser.PureSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.baseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseClause([NotNull] CPP14Parser.BaseClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.baseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseClause([NotNull] CPP14Parser.BaseClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.baseSpecifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseSpecifierList([NotNull] CPP14Parser.BaseSpecifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.baseSpecifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseSpecifierList([NotNull] CPP14Parser.BaseSpecifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.baseSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseSpecifier([NotNull] CPP14Parser.BaseSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.baseSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseSpecifier([NotNull] CPP14Parser.BaseSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.classOrDeclType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrDeclType([NotNull] CPP14Parser.ClassOrDeclTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.classOrDeclType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrDeclType([NotNull] CPP14Parser.ClassOrDeclTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.baseTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseTypeSpecifier([NotNull] CPP14Parser.BaseTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.baseTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseTypeSpecifier([NotNull] CPP14Parser.BaseTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.accessSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessSpecifier([NotNull] CPP14Parser.AccessSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.accessSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessSpecifier([NotNull] CPP14Parser.AccessSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.conversionFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConversionFunctionId([NotNull] CPP14Parser.ConversionFunctionIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.conversionFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConversionFunctionId([NotNull] CPP14Parser.ConversionFunctionIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.conversionTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConversionTypeId([NotNull] CPP14Parser.ConversionTypeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.conversionTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConversionTypeId([NotNull] CPP14Parser.ConversionTypeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.conversionDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConversionDeclarator([NotNull] CPP14Parser.ConversionDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.conversionDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConversionDeclarator([NotNull] CPP14Parser.ConversionDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.constructorInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorInitializer([NotNull] CPP14Parser.ConstructorInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.constructorInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorInitializer([NotNull] CPP14Parser.ConstructorInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.memInitializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemInitializerList([NotNull] CPP14Parser.MemInitializerListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.memInitializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemInitializerList([NotNull] CPP14Parser.MemInitializerListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.memInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemInitializer([NotNull] CPP14Parser.MemInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.memInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemInitializer([NotNull] CPP14Parser.MemInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.meminitializerid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeminitializerid([NotNull] CPP14Parser.MeminitializeridContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.meminitializerid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeminitializerid([NotNull] CPP14Parser.MeminitializeridContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.operatorFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorFunctionId([NotNull] CPP14Parser.OperatorFunctionIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.operatorFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorFunctionId([NotNull] CPP14Parser.OperatorFunctionIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.literalOperatorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralOperatorId([NotNull] CPP14Parser.LiteralOperatorIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.literalOperatorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralOperatorId([NotNull] CPP14Parser.LiteralOperatorIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.templateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateDeclaration([NotNull] CPP14Parser.TemplateDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.templateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateDeclaration([NotNull] CPP14Parser.TemplateDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.templateparameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateparameterList([NotNull] CPP14Parser.TemplateparameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.templateparameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateparameterList([NotNull] CPP14Parser.TemplateparameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.templateParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateParameter([NotNull] CPP14Parser.TemplateParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.templateParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateParameter([NotNull] CPP14Parser.TemplateParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameter([NotNull] CPP14Parser.TypeParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameter([NotNull] CPP14Parser.TypeParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.simpleTemplateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleTemplateId([NotNull] CPP14Parser.SimpleTemplateIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.simpleTemplateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleTemplateId([NotNull] CPP14Parser.SimpleTemplateIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.templateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateId([NotNull] CPP14Parser.TemplateIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.templateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateId([NotNull] CPP14Parser.TemplateIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.templateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateName([NotNull] CPP14Parser.TemplateNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.templateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateName([NotNull] CPP14Parser.TemplateNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.templateArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateArgumentList([NotNull] CPP14Parser.TemplateArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.templateArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateArgumentList([NotNull] CPP14Parser.TemplateArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.templateArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateArgument([NotNull] CPP14Parser.TemplateArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.templateArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateArgument([NotNull] CPP14Parser.TemplateArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.typeNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeNameSpecifier([NotNull] CPP14Parser.TypeNameSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.typeNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeNameSpecifier([NotNull] CPP14Parser.TypeNameSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.explicitInstantiation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitInstantiation([NotNull] CPP14Parser.ExplicitInstantiationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.explicitInstantiation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitInstantiation([NotNull] CPP14Parser.ExplicitInstantiationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.explicitSpecialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitSpecialization([NotNull] CPP14Parser.ExplicitSpecializationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.explicitSpecialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitSpecialization([NotNull] CPP14Parser.ExplicitSpecializationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.tryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTryBlock([NotNull] CPP14Parser.TryBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.tryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTryBlock([NotNull] CPP14Parser.TryBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.functionTryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionTryBlock([NotNull] CPP14Parser.FunctionTryBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.functionTryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionTryBlock([NotNull] CPP14Parser.FunctionTryBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.handlerSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHandlerSeq([NotNull] CPP14Parser.HandlerSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.handlerSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHandlerSeq([NotNull] CPP14Parser.HandlerSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.handler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHandler([NotNull] CPP14Parser.HandlerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.handler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHandler([NotNull] CPP14Parser.HandlerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.exceptionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionDeclaration([NotNull] CPP14Parser.ExceptionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.exceptionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionDeclaration([NotNull] CPP14Parser.ExceptionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.throwExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrowExpression([NotNull] CPP14Parser.ThrowExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.throwExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrowExpression([NotNull] CPP14Parser.ThrowExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.exceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionSpecification([NotNull] CPP14Parser.ExceptionSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.exceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionSpecification([NotNull] CPP14Parser.ExceptionSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.dynamicExceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDynamicExceptionSpecification([NotNull] CPP14Parser.DynamicExceptionSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.dynamicExceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDynamicExceptionSpecification([NotNull] CPP14Parser.DynamicExceptionSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.typeIdList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeIdList([NotNull] CPP14Parser.TypeIdListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.typeIdList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeIdList([NotNull] CPP14Parser.TypeIdListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.noeExceptSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoeExceptSpecification([NotNull] CPP14Parser.NoeExceptSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.noeExceptSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoeExceptSpecification([NotNull] CPP14Parser.NoeExceptSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.theOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTheOperator([NotNull] CPP14Parser.TheOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.theOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTheOperator([NotNull] CPP14Parser.TheOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPP14Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] CPP14Parser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPP14Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] CPP14Parser.LiteralContext context);
}
